steps:
# Install dependencies
- name: 'node:20-slim'
  entrypoint: npm
  args: ['ci']

# Run tests
- name: 'node:20-slim'
  entrypoint: npm
  args: ['test']

# Build the application
- name: 'node:20-slim'
  entrypoint: npm
  args: ['run', 'build']

# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/guidant-mastra-service:$COMMIT_SHA', '.']

# Push the Docker image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/guidant-mastra-service:$COMMIT_SHA']

# Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'guidant-mastra-service'
  - '--image'
  - 'gcr.io/$PROJECT_ID/guidant-mastra-service:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'

# Tag the image as latest
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/guidant-mastra-service:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/guidant-mastra-service:latest']

# Push the latest tag
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/guidant-mastra-service:latest']

images:
- 'gcr.io/$PROJECT_ID/guidant-mastra-service:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/guidant-mastra-service:latest'

timeout: 1800s 