apiVersion: v1
kind: ServiceAccount
metadata:
  name: guidant-mastra-service-sa
  annotations:
    iam.gke.io/gcp-service-account: guidant-mastra-service@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: guidant-mastra-service-workload-identity
spec:
  member: serviceAccount:PROJECT_ID.svc.id.goog[default/guidant-mastra-service-sa]
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: guidant-mastra-service
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: guidant-mastra-service-storage
spec:
  member: serviceAccount:guidant-mastra-service@PROJECT_ID.iam.gserviceaccount.com
  role: roles/storage.objectViewer
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/PROJECT_ID
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: guidant-mastra-service-aiplatform
spec:
  member: serviceAccount:guidant-mastra-service@PROJECT_ID.iam.gserviceaccount.com
  role: roles/aiplatform.user
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/PROJECT_ID
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: guidant-mastra-service-redis
spec:
  member: serviceAccount:guidant-mastra-service@PROJECT_ID.iam.gserviceaccount.com
  role: roles/redis.viewer
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/PROJECT_ID 